### ISSUE TITLE
Plugin creates .clj-kondo and .lsp in non-clojure projects

### ISSUE THREAD

**Issue by sethlivingston** [clojure-lsp/clojure-lsp-intellij#20]
After installing the (wonderful, thank you!) plugin, all of my projects in WebStorm get a `.clj-kondo` and `.lsp` folder:

<img width="541" alt="WW05oQUQ@2x" src="https://github.com/clojure-lsp/clojure-lsp-intellij/assets/574793/32469afb-4c19-45f9-a412-e9c25fe16eb0">

I would only expect this if there was a clojure(script) file in the project.

It's also trying to handle JavaScript rename refactoring:

<img width="442" alt="QXYBwytT@2x" src="https://github.com/clojure-lsp/clojure-lsp-intellij/assets/574793/f9c353fc-ef85-485f-a1d5-39fa257097cc">

**Comment by ericdallo** [comment]
Hey @sethlivingston, thanks for the report!
Hum, interesting, so any non clojure proejct also is starting clojure-lsp unecessarly, I think we should check if the project is a clojure one before that

**Comment by ericdallo** [comment]
About the rename, I'll check if I can bound that only for Clojure language

**Comment by ericdallo** [comment]
Fixed! should be available soon on 0.11.2 in some days
