### ISSUE TITLE
Intellij IDEA hangs on initialization

### ISSUE THREAD

**Issue by hallundbaek** [clojure-lsp/clojure-lsp-intellij#24]
I've been trying to use this plugin a few times. The first few times the "Clojure LSP startup - LSP: Initializing" step caused the IDE to crash. I updated my version, unfortunately I cannot remember from what, but now It doesn't seem to hang, but the task has now been running for 15 minutes.

If this is normal, you should notify users of this expected wait (so they dont go posting issues). And if it is not normal, please advise.

This is my configuration.
```
IntelliJ IDEA 2023.1.5 (Community Edition)
Build #IC-231.9392.1, built on July 25, 2023
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.0-32-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.clojure-lsp (0.12.2)
    IdeaVIM (2.5.1)
    PythonCore (231.9225.4)

Kotlin: 231-1.8.21-IJ9392.1
Current Desktop: i3
```

I am going to try disabling the plugins one by one and report back if that has any effect.

**Comment by hallundbaek** [comment]
The culprit was IdeaVim!

My workaround was to disable the plugin, let the first initialization complete, and then reenable IdeaVim. And now they seem to play nice.

I reckon this issue can either be solved programmatically or by informing users of this incompatibility and its workaround.

**Comment by hallundbaek** [comment]
Additionally, I increased the memory to 8192mb, but that alone had no effect.

**Comment by ericdallo** [comment]
that's pretty weird, clojure-lsp should start ins max 1 or 2 mins usually and next startups should be even faster given the cache, but another plugin affects that? pretty odd... will try to reproduce it here, thanks for the report

**Comment by ericdallo** [comment]
@hallundbaek I really can't repro that, IdeaVim plugin + clojure-lsp-intellij work great for me when testing on some projects like https://github.com/ericdallo/clojure-sample

**Comment by hallundbaek** [comment]
Maybe it's in conjunction with PythonCore, I also had like 15 clj files open at the time. And only 2048 mb heap.

I had previously installed Cursive plugin and had that enabled initially, and I disabled it before enabling closure-lsp, and then un-installed it on a subsequent reboot of IDEA.

**Comment by ericdallo** [comment]
Yeah, without a clean repro it's hard to know what it is, if you manage to repro in a public repo with specific plugins, LMK
