### ISSUE TITLE
Hovering over symbol while holding ctrl key opens definition

### ISSUE THREAD

**Issue by devurandom** [clojure-lsp/clojure-lsp-intellij#27]
I am running the Clojure LSP plugin 1.13.4. When I press and hold ctrl and then move the mouse cursor over a symbol, the definition of that symbol will open (in a new tab). I would expect that to only happen when I click the symbol.

**Comment by ericdallo** [comment]
THanks for the report, I'm aware of this bug, but I couldn't find how to fix it yet

**Comment by ericdallo** [comment]
Finally managed to fix it! available on 1.14.5
