### ISSUE TITLE
CPU eating 100% when opening non clojure project

### ISSUE THREAD

**Issue by gavr123456789** [clojure-lsp/clojure-lsp-intellij#30]
This is my CPU when I opened Kotlin project:
![image](https://github.com/clojure-lsp/clojure-lsp-intellij/assets/30507409/da435f55-3dd9-48c2-87af-f5021c7c8a66)

Disabled Clojure LSP Plugin and restarted IDEA:  
![image](https://github.com/clojure-lsp/clojure-lsp-intellij/assets/30507409/09a04a54-89d8-495e-9a2a-b9f1970beab2)  

I noticed it from the noise of the fans

Idea Ultimate 2023.3.2
Plugin version: 1.14.2

**Comment by ericdallo** [comment]
Is there any public project I can try that? The server was supposed to start only after opening a clj related file

**Comment by ericdallo** [comment]
I suggest you try latest version (2.3.0) which made some significant changes on the plugin
