### ISSUE TITLE
Ability to "Find defprotocol/defmulti implementations" from lsp in idea

### ISSUE THREAD

**Issue by velios** [clojure-lsp/clojure-lsp-intellij#31]
It will be ultra valuable as option to clojure lsp intellij plugin because cursive [cannot do this from 2015](https://github.com/cursive-ide/cursive/issues/437).

Access to https://clojure-lsp.io/features/#find-defprotocoldefmulti-implementations from idea "Inmlementation(s)" or "Find usages" menu actions

**Comment by ericdallo** [comment]
Thanks for the report @velios, that already works in clojure-lsp, I think we just need to make the bridge connection to intellij, I'll take a look at this at the weekend

**Comment by velios** [comment]
I don’t know if this is possible, but it would be great if this function did not conflict with Cursive.

**Comment by ericdallo** [comment]
@velios clojure-lsp-intellij doesn't work with cursive currently

**Comment by ericdallo** [comment]
Done! Available on 2.1.0

**Comment by velios** [comment]
@ericdallo First of all, It's just perfect improvement. Thank you a lot. 

I hope I'm not asking too much by making another suggestion.

1. Is it is possible for commands Find references and Find implementations  move forward to reference/implementation if only one option found. Without show usages dialog.
2. Also interesting is it possible to make Go To Declarations or References command to toggle between references and implementations. Like it already done in IDEA for Go to Declaration and Usages. With suggestion (1) it can dramatically increase navigation speed.
