### ISSUE TITLE
Plugin hangs saying "LSP: Initializing"

### ISSUE THREAD

**Issue by gerdint** [clojure-lsp/clojure-lsp-intellij#35]
When I open my CLJ+CLJS project the plugin the "Clojure LSP statup" just says "LSP: Initializing" indefiniately (and seem to lock up IntelliJ). I collected the logs but there is a lot of them, anyone in particular that can be of help here?

It's a private project so I rather not make it public but I can give access to the relevant plugin dev.

FWIW the same project opens fine in Calva.

**Comment by ericdallo** [comment]
Closing as duplicated of #25, the version that fixed was uploaded to marketplace today, so test it again and if not working, report there with details about your OS/intellij version etc
