### ISSUE TITLE
Syntax highlighting for ClojureDocs examples

### ISSUE THREAD

**Issue by devurandom** [clojure-lsp/clojure-lsp-intellij#38]
**Is your feature request related to a problem? Please describe.**

When I press ^Q on a Clojure function,  the plugin shows me "examples" with code snippets from ClojureDocs. These examples are in plain text.

**Describe the solution you'd like**

The examples could be syntax highlighted to make them more appealing to the eye.

**Comment by ericdallo** [comment]
We need to understand how to support that via Intellij API, this is where the code lives

**Comment by ericdallo** [comment]
@devurandom, the #52 fixed this :)

**Comment by devurandom** [comment]
Beautiful!
![image](https://github.com/clojure-lsp/clojure-lsp-intellij/assets/63082/bbba81d0-2382-48f5-a034-c6cc0f5582e4)

This is not applied to code examples in the docstrings themselves, right?
![image](https://github.com/clojure-lsp/clojure-lsp-intellij/assets/63082/ac077067-8bc5-482c-8104-fd93734209f1)

**Comment by ericdallo** [comment]
@devurandom that happens because the docstring is not in a codeblock, so there is no way for us to know:
![image](https://github.com/clojure-lsp/clojure-lsp-intellij/assets/7820865/85a3c7c7-0c19-4a8a-834c-f5dd53630f36)

**Comment by devurandom** [comment]
Thanks! I thought, because the example is displayed in a box with a grey background and monospace font, that it was treated by the parser like any code block.
