### ISSUE TITLE
Improve naviagation between defrecord implementations and references

### ISSUE THREAD

**Issue by velios** [clojure-lsp/clojure-lsp-intellij#39]
After huge improvement #31 I think it is appropriate to ask the following improvements.

1. Is it is possible for commands Find references and Find implementations move forward to reference/implementation if only one option found. Without show usages dialog.
2. Also interesting is it possible to make Go To Implementations or References command to toggle between implementations and references. Like it already done in IDEA for Go to Declaration and Usages. With suggestion (1) it can dramatically increase navigation speed.

**Comment by ericdallo** [comment]
> Is it is possible for commands Find references and Find implementations move forward to reference/implementation if only one option found. Without show usages dialog.

yes, this is how other editors do with clojure-lsp, we can do that as well.

> Also interesting is it possible to make Go To Implementations or References command to toggle between implementations and references. Like it already done in IDEA for Go to Declaration and Usages. With suggestion (1) it can dramatically increase navigation speed.

Could you elaborate a little bit better? Ctrl + click already does that right?

**Comment by velios** [comment]
> Could you elaborate a little bit better? Ctrl + click already does that right?

In my case there is no option to use only you plugin and I use it with cursive. Not a lot of trouble actually. 
I just remap keymap as shown on screenshot
<img width="698" alt="image" src="https://github.com/clojure-lsp/clojure-lsp-intellij/assets/9293462/66a13517-1f1f-4fd8-8eff-179375022965">
But it be cool if we have another option in keymap like Go To Implementations or References which works as i described above. Move directly to Implementaion/Reference without show dialog if only one option found. Also if i already or reference(or maybe it't easy to do with logic if no reference found, try found implementation) and move to it and vica versa.

**Comment by ericdallo** [comment]
@velios Just released 2.2.0 improving support and fixing 1., I don't think it makes sense for 2. to go to definition since those commands are find-references/implementations, no other editor does that and I think it's against the goal of those commands.

**Comment by velios** [comment]
@ericdallo thank you a lot. Works pretty well. Yes, I really haven’t seen this in other editors. But use already existing `Go to Declaration and Usages` feels awesome. I would be glad if it was possible to move between implementation and reference of defprotocol using the same command `Go to Declaration and Usages`. It will be super convinient.

What about my proposal, in my head `Go To Implementations or References` pretty convinience thing. Let's imagine my cursor already on implementation, so what benefit to me see `no implementation found` popup. Of course it is not, i just confused in my two different shortcuts when exploring my code and jump back and forward between implementations and references
