### ISSUE TITLE
LSP is stuck on "Initializing" step

### ISSUE THREAD

**Issue by lucasfcoelho1** [clojure-lsp/clojure-lsp-intellij#41]
**Describe the bug**
I've installed both `Clojure LSP 2.3.1` and `Clojure REPL 0.1.6`.
I was able to start a REPL, but cannot use the LSP. It is stuck on the `LSP: Initializing` step and I could not navigate through files or functions.

**Screenshots**
![image](https://github.com/afucher/clojure-repl-intellij/assets/11428605/6e4701fc-4619-40a2-89ab-e20927bf8d92)

**Environment (please complete the following information):**
 - IntelliJ Version: IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.clojure-repl (0.1.6)
  manjaro.mpb (1.9)
  com.github.catppuccin.jetbrains_icons (1.4.0)
  com.github.clojure-lsp (2.3.1)
  izhangzhihao.rainbow.brackets (2024.2.2-233)
  com.github.copilot (1.5.1.5285)
  com.mallowigi (94.1.0)
Kotlin: 233.14475.28-IJ

 - OS: MacOS Ventura 13.6.5 (22G621)

**Additional context**
Before install I removed the Cursive plugin to avoid any conflicts, but no success.

**Comment by ericdallo** [comment]
@lucasfcoelho1 can you provide intellij logs when this happens please as described in the issue template?

**Comment by ericdallo** [comment]
BTW could you try completely uninstalling and installing the plugin first?

**Comment by abreumatheus** [comment]
@ericdallo I'm having the same issue on latest version of the plugin. 
How can I provide the Intellij logs you required?

**Comment by ericdallo** [comment]
https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by abreumatheus** [comment]
@ericdallo Couldn't reproduce it being stuck on "Initializing" anymore, but now it's stuck on "Finding Cache". Important to note that it worked fine with this [clojure-example](https://github.com/kenreilly/clojure-example) project, but it won't work with bigger and more complex projects.

I've tried deleting the cache, which made me stuck on "Discovering Classpath" with no new info on the logs.

There is a lot of occurrences of this message here in all logs, could be related?
`INFO - STDOUT - Do not use URL connection as JarURLConnection`

Logs:
[idea_redacted.log](https://github.com/clojure-lsp/clojure-lsp-intellij/files/14827479/idea_redacted.log)

**Comment by ericdallo** [comment]
Thanks for the info, it's weird indeed, I need to repro that somehow, I hope it's not a macos only issue again though.

> There is a lot of occurrences of this message here in all logs, could be related?

It's not related

**Comment by lgcanto** [comment]
Same thing happened to me for both `2.3.2` and `2.3.1`. Tried installing the `2.3.0` version from disk ([download here](https://plugins.jetbrains.com/plugin/22489-clojure-lsp/versions/stable)) and it got back to work

**Comment by ericdallo** [comment]
As far as I manage to understand pairing with @afucher is:
- this seems to happen only with macos again for some reason, I cannot repro that on my Linux
- the main problem is: the `initialize` message is not being sent to server properly, this is done [here](https://github.com/clojure-lsp/clojure-lsp-intellij/blob/dc2b2e2601ce51025c930bcbb412c31b9c49c6f9/src/main/clojure/com/github/clojure_lsp/intellij/server.clj#L115), from what I debugged, the message is being added to the output-ch [here](https://github.com/clojure-lsp/clojure-lsp-intellij/blob/dc2b2e2601ce51025c930bcbb412c31b9c49c6f9/src/main/clojure/com/github/clojure_lsp/intellij/client.clj#L100), **but** we never receive it from the channel [here](https://github.com/clojure-lsp/clojure-lsp-intellij/blob/dc2b2e2601ce51025c930bcbb412c31b9c49c6f9/src/main/clojure/com/github/clojure_lsp/intellij/client.clj#L170), never writing to the OutputStream...

I added sleeps and lots of logs but couldn't find the reason why yet.

**Comment by abreumatheus** [comment]
@ericdallo I tried downgrading to 2.3.0 like @lgcanto, but it still didn't work.
Damn macOS. This is almost making me change to linux hahaha

**Comment by ericdallo** [comment]
@abreumatheus I'm testing different things in [this branch](https://github.com/clojure-lsp/clojure-lsp-intellij/tree/test-logs-to-output-chan) and asking for a coworker that has mac to test, I'll keep this issue updated if any findings

**Comment by abreumatheus** [comment]
@ericdallo I'm also your coworker btw. If you need anything feel free to reach out. 😁

**Comment by ericdallo** [comment]
@abreumatheus #42 should fix it 🙌🏻 , I'll wait for any of you test and report

**Comment by ericdallo** [comment]
This will be fixed on 2.3.3 release
