### ISSUE TITLE
Autocomplete ignores leading pipe symbol (`|`) for namespaced symbols

### ISSUE THREAD

**Issue by eduardolevygp** [clojure-lsp/clojure-lsp-intellij#46]
**Describe the bug**
When a symbol from a different namespace starts with a pipe symbol, the autocomplete ignores it when you type it, causing duplication when you select the autocomplete item.

**To Reproduce**
1. Create a namespace called `foo`, with a symbol called `|bar` in it.
2. In another namespace, require `foo` and type `foo/`, then trigger autocomplete
3. Type `|ba` and select `|bar` option on the autocomplete list
4. It'll result in `foo/||bar`

**Expected behavior**
Consider the pipe symbol for the search when typed, removing it when it's replaced with the auto-completed value, avoiding duplication.

**Desktop (please complete the following information):**
 - OS: `macOS 13.6.6`
- Intellij version: `IntelliJ IDEA 2023.3.5 (Community Edition)`
- Plugin version: `2.3.8`

**Comment by ericdallo** [comment]
Fixed on 420dd7b
