### ISSUE TITLE
Change color of commented code with `#_`

### ISSUE THREAD

**Issue by mtsbarbosa** [clojure-lsp/clojure-lsp-intellij#47]
**Is your feature request related to a problem? Please describe.**
When adding `#_` before a code to comment it, the color does not change

**Describe the solution you'd like**
To have the same gray coloring of the `;` commented lines

**Describe alternatives you've considered**

**Additional context**

**Comment by ericdallo** [comment]
I'm aware of this bug but could not find a way to fix it yet, we should change IntelliJ lexer used in our library to achieve that

**Comment by nukurt** [comment]
Feel free to wander around the wreckage of https://github.com/projectileboy/clo-jet/tree/master/src/com/bitbakery/clojet/lexer; not sure if there anything useful in there or not, but the lexer and parser were pretty solid iirc.

**Comment by ericdallo** [comment]
Unfortunately, I think that lexer doesn't support form comments :/

**Comment by ericdallo** [comment]
@mtsbarbosa I managed to partially fix it supporting one level of form comment which should attend most of the cases, feel free to create a new issue for the remaining feature

![2024-11-11_19-05](https://github.com/user-attachments/assets/f0bf3acc-599c-40ea-bb93-1acd8e108b3c)

**Comment by mefryar** [comment]
Thanks, @ericdallo! I've created https://github.com/clojure-lsp/clojure-lsp-intellij/issues/58 to request support for changing to grey single forms that are more than one string.
