### ISSUE TITLE
"Create namespace and function" not working

### ISSUE THREAD

**Issue by mefryar** [clojure-lsp/clojure-lsp-intellij#51]
**Describe the bug**
The "Code Action" option "Create namespace and function" does not create a new namespace.

**To Reproduce**
1. Clone project [`ericdallo/clojure-sample`](https://github.com/ericdallo/clojure-sample)
2. Open `clojure-sample.lsp.code-actions.d`
3. Create `code-actions.e/code-action-e-var`
4. Place cursor at beginning of line, use ⌥ + Enter to open Code Actions
5. Click "Create namespace 'code-actions.e' and function 'code-action-e-var'"

**Expected behavior**
New namespace `clojure-sample.lsp.code-actions.e` is created with `(def code-action-e-var)`.

**Screenshots**
<img width="1792" alt="image" src="https://github.com/clojure-lsp/clojure-lsp-intellij/assets/21371788/ed90d50d-32ce-40a8-8765-ea3a827b0ffc">

**Desktop (please complete the following information):**
clojure-lsp-intellij: 2.4.5
clojure-repl-intellij: 1.3.1
IntelliJ IDEA: 2024.1
macOS: Sonoma 14.4.1
 

**IntelliJ Log**
Nothing is logged to `idea.log`.

**Comment by ericdallo** [comment]
This should be fixed on next release
