### ISSUE TITLE
Don't check the remote Clojure-LSP everytime.

### ISSUE THREAD

**Issue by DavidAlphaFox** [clojure-lsp/clojure-lsp-intellij#56]
**Is your feature request related to a problem? Please describe.**
The clojure-lsp-plugin checks the Clojure-LSP's version every time. When the network can't be reached, it can't use the clojure-lsp program in the local.

**Describe the solution you'd like**
Could we add an option in settings, so we could upgrade it manually and don't check it every time. And if we find a clojure-lsp program in the local match the version in clojure-lsp-vserion file when the network can't be reached, we can use the local.

**Comment by ericdallo** [comment]
@DavidAlphaFox What about we try to update and if network fail we use the one available? would that be enough for you?

**Comment by ericdallo** [comment]
Done! available in 2.6.1
